"""menambah booking table

Revision ID: 0e4cf30ed691
Revises: 4c960b45b775
Create Date: 2023-01-05 10:51:13.659894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4cf30ed691'
down_revision = '4c960b45b775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.BigInteger(), nullable=False, auto_increment=True),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('jam_mulai', sa.DateTime(), nullable=True),
    sa.Column('jam_akhir', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
