"""update booking time type

Revision ID: 218371f41c60
Revises: 753513197bcd
Create Date: 2023-01-08 23:20:31.683501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '218371f41c60'
down_revision = '753513197bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal', sa.Date(), nullable=False))
        batch_op.alter_column('jam_mulai',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               nullable=False)
        batch_op.alter_column('jam_akhir',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('jam_akhir',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('jam_mulai',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('tanggal')

    # ### end Alembic commands ###
