"""tambah atribut isi_slot

Revision ID: 2d00ff6c143a
Revises: 98af243c1c25
Create Date: 2023-01-05 11:07:06.114119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d00ff6c143a'
down_revision = '98af243c1c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isi_slot', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('isi_slot')

    # ### end Alembic commands ###
