"""tambah data invoice

Revision ID: 753513197bcd
Revises: e7c3862d42cf
Create Date: 2023-01-08 19:16:37.756439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753513197bcd'
down_revision = 'e7c3862d42cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pembayaran', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_booking', schema=None) as batch_op:
        batch_op.drop_column('id_pembayaran')

    # ### end Alembic commands ###
