"""ganti userid dengan email

Revision ID: 9002123fa30e
Revises: b911d12a436c
Create Date: 2023-01-09 00:24:25.704028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9002123fa30e'
down_revision = 'b911d12a436c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=False))
        batch_op.create_index(batch_op.f('ix_booking_email'), ['email'], unique=True)
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_booking_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
