"""update detail booking with input tanggal

Revision ID: b911d12a436c
Revises: 218371f41c60
Create Date: 2023-01-09 00:09:38.399464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b911d12a436c'
down_revision = '218371f41c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('jam_mulai', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('jam_akhir', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_booking', schema=None) as batch_op:
        batch_op.drop_column('jam_akhir')
        batch_op.drop_column('jam_mulai')
        batch_op.drop_column('tanggal')

    # ### end Alembic commands ###
