"""fix email di booking supaya tidak unique

Revision ID: ba8e6fea4405
Revises: c2ec8f59c3ce
Create Date: 2023-01-10 12:25:52.943523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8e6fea4405'
down_revision = 'c2ec8f59c3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index('ix_booking_email', ['email'], unique=False)

    # ### end Alembic commands ###
